### ISSUE TITLE
Mobile app

### ISSUE THREAD

**Issue by rameshbas** [OnsenUI/angular2-onsenui-kitchensink#2]
Finally its atrted working after installing all dependencies manully. It works on pc  with a local host:3000
How does one build and put it on my phone? Monaca debugger is active and works with other examples but this one. How do you build and apk with this?

**Comment by masahirotanaka** [comment]
Thanks for the feedback @rameshbas. Have you tried installing Monaca CLI (`npm install monaca`) and create a kitchensink project by `monaca create` command?

**Comment by IliaSky** [comment]
Hi @rameshbas. Sorry for the delayed answer. Actually this repo showcases only Onsen UI 2 and Angular 2, without actually wrapping them in a cordova (mobile application) project. 

Since you mentioned Monaca debugger I am guessing that you are already familiar with Monaca CLI. 
This is the prototype for the kitchensink template in Monaca CLI, but as I already mentioned it is not a cordova project itself. Making this project into an apk is not very complex, but a relatively lengthly process, so instead of doing that I would suggest just creating a new one from the cli.

**To do that you need**:

```
npm install -g monaca         # Update monaca cli
monaca create my-kitchensink  # Create a new project
monaca remote build           # And finally build
```

If you need some more information here are the [Docs](https://docs.monaca.io/en/quick_start/cli/building_app/) for the last step.

**Very long alternative - using cordova locally**:
Add `<script src="cordova.js"></script>` to `src/index.html`

```
npm install -g cordova          # Install cordova
cordova create my-kitchensink   # Create a new project
webpack                         # Build the current project
rm -rf my-kitchensink/www/*     # Clear the new project
cp -r src/* my-kitchensink/www  # Copy the source files
cp dist/* my-kitchensink/www    # Copy the bundled files
cd my-kitchensink               # Go to the new project's folder
cordova add platform android    # Add android platform
cordova build ios/android       # And finally build the apk
```

The choice is yours, but I think the first option looks simpler.

If you have further questions feel free to ask again.

**Comment by rameshbas** [comment]
Thanks. I will try. For Angular 1 Monaca is great. for Angular2 it is not simple

**Comment by IliaSky** [comment]
Yeah, unfortunately. Lets hope it becomes simpler in time :)
